name: End-to-End

on: [push]

jobs:
  ng-e2e:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.2
        ports:
          - '27017-27019:27017-27019'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Gradle artifacts (downloaded JARs, the wrapper, and any downloaded JDKs)
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/jdks
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle/') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./client/package-lock.json

    - name: Run e2e tests
      uses: cypress-io/github-action@v5
      with:
        start: ${{ github.workspace }}/server/gradlew run -p ${{ github.workspace }}/server/
        command: npm run e2e
        working-directory: ./client
